### ISSUE TITLE
write() method and leading whitespace

### ISSUE THREAD

**Issue by makkus** [pavdmyt/yaspin#16]
I'm trying to use the `spinner.write()` method to output sorta hierarchical text, but that proves difficult as it strips every input string (here: https://github.com/pavdmyt/yaspin/blob/dd5ad76c7f7a89dbed22427affad6d350c473e41/yaspin/yaspin.py#L193).

Is there a reason for this, or could this strip() command be removed? I'd be also happy with an option that defaults to strip, but lets me disable it. It's a trivial change, but I'd be happy to provide a pull request if necessary, and if my proposed change is acceptable.

**Comment by pavdmyt** [comment]
Hi @makkus 

Thanks for raising this up!

Can you please provide an example of your use case?
It was designed for writing one line at a time, was not actually thinking about printing multi-line input at a time.

**Comment by makkus** [comment]
I'm happy with a single line output, as I can just iterate through my lines and do a `write` on each of them. What I'd need is for the .strip() command to be gone or configurable, so I can output stuff like:

```
- task: 'task1'
    - subtask: 'subtask1'
- task: 'task2'
   - subtask: 'subtask2'
...
...
```
Currently that is not possible, because all of the indented lines are stripped, and I'd get:

```
- task: 'task1'
- subtask: 'subtask1'
- task: 'task2
- subtask: 'subtask2'
...
...

Does that make sense?
```

**Comment by pavdmyt** [comment]
Got it. Let's proceed with passing two optional arguments `spinner.write(lstrip=True, rstrip=True)` to make things configurable. I'll be able to work on this at next the week. Feel free to open a PR if you'd like to.
