### ISSUE TITLE
Transitive dependency (termcolor) does not have wheel

### ISSUE THREAD

**Issue by matthewdeanmartin** [pavdmyt/yaspin#171]
I'm working on getting security packages to have the option of installing with only wheels (it's more secure that way), ref. [Jake](https://github.com/sonatype-nexus-community/jake/issues/72) which means the whole dependency graph needs to have wheels

yaspin's dependency on termcolor (which has no wheels and has no maintainer, so it is hard for me to get a wheel in termcolor)

I did create a fork, [termcolor-whl](https://pypi.org/project/termcolor-whl/) so you could switch to that or venderize termcolor.

Without something like that, people who depend on yaspin would have to vendorize to get around the problem.

**Comment by pavdmyt** [comment]
Hi @matthewdeanmartin 

Thanks for pointing this out and detailed description for potential security issues :+1: 
I'll probably vendor termcolor, as it was before this commit: https://github.com/pavdmyt/yaspin/pull/133/commits/d19bbe78c5e0bd9c7b18242e4872ac59380fa7f8

**Comment by pavdmyt** [comment]
The fix will be included into the next release.
