### ISSUE TITLE
Unexpected output characters

### ISSUE THREAD

**Issue by freegor** [pavdmyt/yaspin#176]
We are using the yaspin in our library. It runs on any notebook, like jupyter or Databricks, on MacOS or Cloud based.
Generally yaspin works but some strange output even if I use your examples from the README file:
<img width="881" alt="Screen_Shot_2022-01-09_at_13_16_25" src="https://user-images.githubusercontent.com/2372341/148680312-9efff0dc-0f2e-48e0-a239-febedd983b70.png">

so is it artifacts which I can remove?
Actually I have a problem with some number and 'h' when I use yaspin in my package.

**Comment by gailuron1964** [comment]
Noticed the same thing. Funnily I only reproduce this with Jupyter Notebook. Not with Google Colab. freegor, did you find a workaround ?

**Comment by pavdmyt** [comment]
Fixed in #193 
Will be included into the next yaspin release.
