### ISSUE TITLE
Consider switching back to `termcolor`

### ISSUE THREAD

**Issue by felixonmars** [pavdmyt/yaspin#211]
The original `termcolor` project has resurrected and providing a wheel as well, now. The `termcolor-whl` one, however, seems to be inactive as the open issue/pr were left unanswered for a long time.

**Comment by pavdmyt** [comment]
Thanks for letting me know. It is an unexpected surprise that `termcolor` was resurrected after 11 years of silence.
I'll consider it for the next yaspin release.

**Comment by pavdmyt** [comment]
Implemented by https://github.com/pavdmyt/yaspin/pull/218, included into latest release: https://github.com/pavdmyt/yaspin/releases/tag/v2.3.0
