### ISSUE TITLE
Name not defined in 3.0

### ISSUE THREAD

**Issue by janpipek** [pavdmyt/yaspin#230]
Hello, I am seeing this message:

```
File "[EDITED]/yaspin/core.py", line 175, in __call__
    return cast(Fn, inner)
NameError: name 'Fn' is not defined
```

It seems that `cast` requires the type to be defined outside the TYPE_CHECKING condition.
Should I post a fixing PR?

All the best,
Jan

Version 3.0, Python 3.9

**Comment by pavdmyt** [comment]
@janpipek thanks for the fix! Will include this into the next yaspin release.
