### ISSUE TITLE
Is there a way of custom spinners?

### ISSUE THREAD

**Issue by sniff122** [pavdmyt/yaspin#30]
I am curious if you can specify custom spinners in the form of a list variable of the "frames" of the animation with the first list value the delay for the animation.

**Comment by pavdmyt** [comment]
@sniff122 

Sure! Here is an example:

```python
# -*- coding: utf-8 -*-
import time
from yaspin import yaspin, Spinner

# Compose new spinners with custom frame sequence and interval value
sp = Spinner(["😸", "😹", "😺", "😻", "😼", "😽", "😾", "😿", "🙀"], 200)

with yaspin(sp, text="Cat!"):
    time.sleep(3)
```

2nd argument to `Spinner` specifies delay for the animation in milliseconds.

You can also check [examples](https://github.com/pavdmyt/yaspin/tree/master/examples) for the reference.
