### ISSUE TITLE
pipenv's patch to prevent AttributeError in _register_signal_handlers

### ISSUE THREAD

**Issue by jayvdb** [pavdmyt/yaspin#32]
pipenv applies a patch to their vendored copy of tomlkit, and it seems that it has parts which belong here, but havent been raised here.

The patch is https://github.com/pypa/pipenv/blob/master/tasks/vendoring/patches/vendor/yaspin-signal-handling.patch , but only the following bit looks like it belongs here:

```diff
diff --git a/pipenv/vendor/yaspin/core.py b/pipenv/vendor/yaspin/core.py
index d01fb98e..06b8b621 100644
--- a/yaspin/core.py
+++ b/yaspin/core.py
@@ -369,11 +375,14 @@ class Yaspin(object):
         # SIGKILL cannot be caught or ignored, and the receiving
         # process cannot perform any clean-up upon receiving this
         # signal.
-        if signal.SIGKILL in self._sigmap.keys():
-            raise ValueError(
-                "Trying to set handler for SIGKILL signal. "
-                "SIGKILL cannot be cought or ignored in POSIX systems."
-            )
+        try:
+            if signal.SIGKILL in self._sigmap.keys():
+                raise ValueError(
+                    "Trying to set handler for SIGKILL signal. "
+                    "SIGKILL cannot be cought or ignored in POSIX systems."
+                )
+        except AttributeError:
+            pass
 
         for sig, sig_handler in iteritems(self._sigmap):
             # A handler for a particular signal, once set, remains
```

I am quite confident this is correct and needed here, as `signal` module documentation indicates that the list of signals in this module is host specific, and I am quite sure SIGKILL doesnt exist on Windows.

It appears the author of this part of the patch was @techalchemy .

Ideally they should be submit the patch, or someone elses should submit it with the patch author set to the correct author.

**Comment by pavdmyt** [comment]
Hi @jayvdb 

I've reviewed the changes in `yaspin` at `pipenv/vendor`. As far as I understand, this is an attempt to provide Windows compatibility for `yaspin`. The above-mentioned patch is a tiny step toward this goal. There are many other edge-cases (like usage of `vistir.cursor` module in `pipenv/vendor/yaspin` for handling cursor support under Windows).

I believe that if we want to implement Windows support for `yaspin`, it should be more centralized effort, like single PR, covered with tests and CI pipeline for Windows platform. I'll open a separate issue with such feature request. Unfortunately, currently I don't have a capacity to work on implementation for this feature.

As I see, the absolute minimum plan towards Windows support is as follows:
- apply the [patch](https://github.com/pypa/pipenv/blob/master/tasks/vendoring/patches/vendor/yaspin-signal-handling.patch) for handling signals
- use [vistir/cursor](https://github.com/sarugaku/vistir/blob/master/src/vistir/cursor.py) module for cursor support
- implement (or find the replacement for) [termcolor](https://pypi.org/project/termcolor/) features in Windows environment
- unittests for all `yaspin` features under Windows
- CI pipeline for tests under Windows

**Comment by techalchemy** [comment]
Agreed. I have plans to put a PR together when I have time and am confident I’ve hit the edge cases

**Comment by techalchemy** [comment]
As an additional sidenote @pavdmyt I do have full functionality for yaspin working on windows, although not all of the spinners work due to unicode support (I default to `bouncingBar`) -- this is the only spinner library that does anything close to what I want so props to you for putting it together and thanks to @jayvdb for tracking down the vendoring issues on our end, it is greatly appreciated

**Comment by techalchemy** [comment]
@pavdmyt -- windows support currently depends on colorama in vistir. I'm happy to PR this in, but realized you have no dependencies currently.  Would that be an issue?

**Comment by pavdmyt** [comment]
@techalchemy I believe it is Ok to use `colorama`. Actually `termcolor` is used by `yaspin` and it is vendored (as a single module).

The only concern I have is that I don't want to change the current yaspin's API for colors. Is it possible to achieve this with `colorama`?

**Comment by pavdmyt** [comment]
Closing in favor of #33
