### ISSUE TITLE
Unittesting custom signal handlers

### ISSUE THREAD

**Issue by justinlulejian** [pavdmyt/yaspin#44]
I have code that handles keyboard interrupts with ctrl+c:

``` 
# my_code.py

def my_signal_handler(signum, frame, spinner):
  # does some things

def run_a_long_running_command()
  with yaspin.yaspin(
        sigmap={
            signal.SIGINT: my_signal_handler
        }, color="yellow").point as spinner:
    time.sleep(10)
```
And a unit test (e.g. my_code_test.py) that is attempting to engage the lines in `my_signal_handler()` to assert something is done inside it.

But I haven't been able to make this happen when using the unittest framework. I first tried to raise a KeyboardInterrupt, but realized that signals are not an exception. I then realized that making `time.sleep(10)` instead do `os.kill(os.getpid(), signal.SIGINT)` doesn't work either. Is there a way to manually cause the signal to occur from another file?

**Comment by pavdmyt** [comment]
Hi @justinlulejian 

Probably this answer can help (using `subprocess.Popen` to spawn a separate process with registered signal handler): https://stackoverflow.com/a/26159031
