### ISSUE TITLE
redirected output has spinners

### ISSUE THREAD

**Issue by coreybrett** [pavdmyt/yaspin#45]
My redirected output has...

`[33m⠋[0m [K
[33m⠙[0m [K
[33m⠹[0m [K
[33m⠸[0m [K
[33m⠼[0m [K
[33m⠴[0m [K
[33m⠦[0m [K
[33m⠧[0m [K
[33m⠇[0m [K`

Is there anyway to get rid of that?

**Comment by pavdmyt** [comment]
Hi @coreybrett 

Can you please provide more context about the issue? Like following:

- Code sample
- How it is executed
- Python version

Also, you can find more about current redirect issues and limitations here: https://github.com/pavdmyt/yaspin/issues/31

**Comment by pavdmyt** [comment]
Closing as a duplicate of #31
