### ISSUE TITLE
Scroll the terminal while the spinner spins

### ISSUE THREAD

**Issue by DrPaprikaa** [pavdmyt/yaspin#47]
While the spinner is spinning, I can't scroll the terminal to read the previously printed lines (the spinner constantly brings me back to the last line). Is there a way around that ?

**Comment by pavdmyt** [comment]
Hi @DrPaprikaa, thanks for reporting the issue!

Which OS and terminal application you're using? 

For example, I'm on macOS Mojave (version 10.14.6) with iTerm v3.3.9 and see no issues while scrolling the terminal tab during spinner is spinning.

**Comment by DrPaprikaa** [comment]
Hi @pavdmyt, thanks for the quick reply !
I'm on Windows using IntelliJ IDEA 2019.2.3.

**Comment by pavdmyt** [comment]
So, you're using a terminal built in IntelliJ IDEA?

Sorry for late response, I've somehow missed your answer (

**Comment by DrPaprikaa** [comment]
No problem, I was talking about the output window in IntelliJ IDEA (not the terminal)

**Comment by DrPaprikaa** [comment]
Hi, any update on this issue ?

**Comment by pavdmyt** [comment]
I believe this issue is caused be terminal plugin implementation in IntelliJ IDEA. Unfortunately, I can't reproduce this issue, since I'm not using IntelliJ IDEA. But I'd suggest to try another terminal plugin or tweak settings of existing one.

**Comment by sebageek** [comment]
Yaspin writes a line of text each time the spinner moves. I guess the IntelliJ terminal is configured for `Scroll on output`, meaning each time the spinner spins the terminal scrolls to the bottom. @DrPaprikaa I think you have to see if you can disable this in our terminal. There is not much Yaspin can do about it.
