### ISSUE TITLE
passing variable in the shortlink

### ISSUE THREAD

**Issue by therealelyayo** [pavdmyt/yaspin#57]
would it be possible to append ?email=jackson@be.com to these redirect and then using the domain of the email to redirect somewhere ,
example?email=t@gmail.com would goto gmail.com

and t@yahoo.com shuld got yahoo.com

would that be possible

**Comment by pavdmyt** [comment]
I'm not sure that issue description is clear to me. Can you please provide more details or describe your particular use case more clearly?
