### ISSUE TITLE
tests and examples are distributed in wheels and installed

### ISSUE THREAD

**Issue by McSinyx** [pavdmyt/yaspin#59]
Hi, I am not familiar with Poetry but somehow the following lines cause `examples` and `tests` to be distributed in wheels:

https://github.com/pavdmyt/yaspin/blob/fe14dc5e619fa204c9c8eea6e2ac603a7bb3d359/pyproject.toml#L17-L18

**Comment by pavdmyt** [comment]
Hi,

Thanks for reporting this! Migrated to Poetry recently (also not very familiar) and didn't catch this.

**Comment by pavdmyt** [comment]
The fix will be included in release `0.18.0`.

**Comment by McSinyx** [comment]
Thanks, that was a quick fix!
