### ISSUE TITLE
yaspin with pyinstaller

### ISSUE THREAD

**Issue by haipas** [pavdmyt/yaspin#77]
Hello,
I use yaspin in my code. Thanks a lot! 
I want to make my program executable with pyinstaller but the spinners are only cryptically displayed. Do I have to provide the pyinstaller with more data from yaspin?

**Comment by pavdmyt** [comment]
Hello @haipas,

Can you please provide more details about the issue? How exactly you're building the executable, how you're using yaspin and what output do you have?

**Comment by haipas** [comment]
Hi @pavdmyt,
i used the following example:

```
import time
from random import randint
from yaspin import yaspin

with yaspin(text="Loading", color="yellow") as spinner:
    time.sleep(2)  # time consuming code

    success = randint(0, 1)
    if success:
        spinner.ok("✅ ")
    else:
        spinner.fail("💥 ")
```
and build this script with `pyinstaller spinner.py`

Output is: [K[?25hOK [0m

I think the problem is that the standard windows cmd does not support utf-8. With cmder it works fine.

**Comment by pavdmyt** [comment]
You can also check whether it's a utf-8 issue by replacing utf-8 symbols from script to ascii.

I'm closing the issue, feel free to reopen if needed.
